apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: dotroute-relations
spec:
  template:
    spec:
      containers:
      - name: gui
        image: dotroute-relations-gui
        imagePullPolicy: Never
