apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: dotroute-relations
  labels:
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: dotroute-relations-gui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /api/health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            path: /api/health
            port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: www
  namespace: dotroute-relations
  labels:
    app: gui
spec:
  selector:
    app: gui
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
